- public/index.js
- src/v1/platforms/AWS/AWS.ts
- src/v1/platforms/GoogleDrive/GoogleDrive.ts
> PIM-215: fix multi file upload

- src/v1/platforms/Office365/Office365.ts
- src/v1/routers/uploadRouter.ts
Behhh gone! Rogue error statement was left into the codebase when trying to force an error to test error handling on PLM
> MVP-21290: O365: Behhh error reappearing

- package-lock.json
- package.json
- src/v1/customTypes/jsforce-propel.ts
- src/v1/platforms/AWS/AWS.ts
- src/v1/utils/JsForce.ts
new bucket > create cdn > attach bucket to cdn > write back to org with cdn url
> PIM-241: Automatically create and link a new CDN distribution to new S3 bucket

- src/v0/customTypes/InstanceMap.d.ts
- src/v1/platforms/AWS/AWS.ts
- src/v1/platforms/Office365/Office365.ts
- src/v1/platforms/StoragePlatform.ts
- src/v1/routers/fileRouter.ts
Orrganise AWS uploads according to org Ids, sharing the same s3 bucket
> PIM-298: PIM | Cloud Storage | S3 Convert to folder based

- public/index.css
- public/index.html
- UI fixes for button and progress bar
_To be merged with https://github.com/PropelPLM/PIM/pull/471_
> PIM-516: PIM | Enrich Admin | Data Import Uploads

- src/v1/utils/JsForce.ts
Make JSForce package use our own managed package's namespace, not the overall org's.
> PIM-560: Digital Assets Import | Can't Import digital assets in UAT Package environment

- src/v1/routers/uploadRouter.ts
- src/v1/utils/InstanceManager.ts
This fixes the lack of auto refresh whenever things are saved
> allow falsey values to be stored in Redis

- src/v1/utils/JsForce.ts
Fixed on QA (only env it occurs). orgNamespace was '', passing the null check and deleting all the valid fields which failed the SF level required fields check.
> PIM-715: Digital Assets Upload error

- public/index.html
Updated jquery version since version 3.4.1 is vulnerable for Cross-site Scripting
> PIM-708: Insecure Software Version Vulnerability

- src/v1/customTypes/InstanceMap.d.ts
- src/v1/utils/JsForce.ts
add ability to replace(upsert) record
> PIM-693: Digital Asset Upload modal shouldn't include Categories for Replace Asset functionality

- package-lock.json
- package.json
> reverting the snyk suggestion

- public/ChimeraToken.txt
Chimera scanner access for salesforce security review process.
> PIM-931 access for Chimera scanner

- package-lock.json
- package.json
- src/v1/utils/JsForce.ts
looks like a few issues that were easily fixed.
> MVP-23773 fixing the error and rebuilding the lock

- src/v1/utils/JsForce.ts
Support for writing tokens to old custom setting `Cloud_File_Storage__c`. Needed for customers who have not upgraded.
> MVP-24303: Token write back for older google integration customers that do not have Cloud_File_Storage__c

- src/v1/platforms/AWS/AWS.ts
Generates a thumbnail for videos upon upload.
> [SUPPORT PR] PIM-1069: Make Asset View available on DA list page

- src/v1/utils/JsForce.ts
Calls the new [Configuration API](https://github.com/PropelPLM/PLM/pull/11857) to update protected custom settings within managed packages
> MVP-24302: Write back for protected custom settings

- src/v1/utils/InstanceManager.ts
Referring to https://github.com/PropelPLM/CloudFileStorage/commit/a25c3ceb86cc86b40495296a6d5ef97c426a3149
> MVP-26733: Heroku Document: Redis upgrade caused outage

- src/v1/routers/uploadRouter.ts
Add error message parsing for user-friendly error message upon upload error
> PIM-1750: PIM | Digital Asset | Flag for the first 100 records

- src/v1/customTypes/InstanceMap.d.ts
- src/v1/routers/uploadRouter.ts
- Prevent uploading of digital assets in the event that the upload will result in exceeding of digital asset limit
- This is done by deferring the uploading and creation of assets until after the files have been counted and the count is validated to be under the upload limit
https://github.com/user-attachments/assets/bd328a1d-dc76-49ec-a64c-ef04904fa0ff
PR in PIM repo: https://github.com/PropelPLM/PIM/pull/1634
> PIM-1750-2: PIM | Digital Asset | Flag for the first 100 records

- src/v1/utils/JsForce.ts
Reverts PropelPLM/CloudFileStorage#79
> Revert "MVP-27356: Attachments | Implement Extended File Name Logic (20685) in new field"
